### ISSUE TITLE
No respond.

### ISSUE THREAD

**Issue by TheNotify** [HunteRoi/discord-mailbox#11]
Hello there! For some reason, it does not reply that a new modmail has opened when I send a message on my bot's dm. It's like it doesn't do anything even though I did check if I did any typos.
Also, can you give me your discord username so that I can add you? It will be easier to talk there. It's okay if you don't want to.

**Comment by HunteRoi** [comment]
Hey :) If you want to avoid using threads, remove the threadOptions property in the manager's options : 
![image](https://user-images.githubusercontent.com/32441291/225672543-48fd5dfc-e6ac-43f0-9935-4dc44585c8cd.png)
